package com.eaglesakura.andriders.dao.bkvs;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DB_KEY_VALUE_DATA.
 */
public class DbKeyValueData {

    /** Not-null value. */
    private String key;
    private byte[] value;
    /** Not-null value. */
    private java.util.Date date;

    public DbKeyValueData() {
    }

    public DbKeyValueData(String key) {
        this.key = key;
    }

    public DbKeyValueData(String key, byte[] value, java.util.Date date) {
        this.key = key;
        this.value = value;
        this.date = date;
    }

    /** Not-null value. */
    public String getKey() {
        return key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(String key) {
        this.key = key;
    }

    public byte[] getValue() {
        return value;
    }

    public void setValue(byte[] value) {
        this.value = value;
    }

    /** Not-null value. */
    public java.util.Date getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
