package com.eaglesakura.andriders.dao.tkvs;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.eaglesakura.andriders.dao.tkvs.DbKeyValueData;

import com.eaglesakura.andriders.dao.tkvs.DbKeyValueDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dbKeyValueDataDaoConfig;

    private final DbKeyValueDataDao dbKeyValueDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dbKeyValueDataDaoConfig = daoConfigMap.get(DbKeyValueDataDao.class).clone();
        dbKeyValueDataDaoConfig.initIdentityScope(type);

        dbKeyValueDataDao = new DbKeyValueDataDao(dbKeyValueDataDaoConfig, this);

        registerDao(DbKeyValueData.class, dbKeyValueDataDao);
    }
    
    public void clear() {
        dbKeyValueDataDaoConfig.getIdentityScope().clear();
    }

    public DbKeyValueDataDao getDbKeyValueDataDao() {
        return dbKeyValueDataDao;
    }

}
