#! /bin/sh
RELEASE_NAME=eglibrary-android-dropbox.jar
RELEASE_DIR=release
LICENSE_FILENAME=LICENSE_$RELEASE_NAME

if [ -f "./javadoc.xml" ]; then
# export javadoc
    ant -f ./javadoc.xml
fi

android update lib-project -p ./

ant clean
ant release
if [ $? -ne 0 ]; then
    echo "build fail..."
    exit 1
fi
cd bin/
zip -u -r classes.jar ../src/**
zip -u -r classes.jar ../doc/**
cp ../../LICENSE ./$LICENSE_FILENAME
zip -u -r classes.jar ./$LICENSE_FILENAME
rm ./$LICENSE_FILENAME
mv classes.jar ../../$RELEASE_DIR/$RELEASE_NAME

cd ../
rm -rf ./doc
