package com.eaglesakura.android.dao.net;

import com.eaglesakura.android.dao.net.DbFileBlock;
import com.eaglesakura.android.dao.net.DbFileBlockDao;
import com.eaglesakura.android.dao.net.DbNetCache;
import com.eaglesakura.android.dao.net.DbNetCacheDao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dbNetCacheDaoConfig;
    private final DaoConfig dbFileBlockDaoConfig;

    private final DbNetCacheDao dbNetCacheDao;
    private final DbFileBlockDao dbFileBlockDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dbNetCacheDaoConfig = daoConfigMap.get(DbNetCacheDao.class).clone();
        dbNetCacheDaoConfig.initIdentityScope(type);

        dbFileBlockDaoConfig = daoConfigMap.get(DbFileBlockDao.class).clone();
        dbFileBlockDaoConfig.initIdentityScope(type);

        dbNetCacheDao = new DbNetCacheDao(dbNetCacheDaoConfig, this);
        dbFileBlockDao = new DbFileBlockDao(dbFileBlockDaoConfig, this);

        registerDao(DbNetCache.class, dbNetCacheDao);
        registerDao(DbFileBlock.class, dbFileBlockDao);
    }

    public void clear() {
        dbNetCacheDaoConfig.getIdentityScope().clear();
        dbFileBlockDaoConfig.getIdentityScope().clear();
    }

    public DbNetCacheDao getDbNetCacheDao() {
        return dbNetCacheDao;
    }

    public DbFileBlockDao getDbFileBlockDao() {
        return dbFileBlockDao;
    }

}
