#! /bin/sh
RELEASE_NAME=eglibrary-android-api8-splib.jar
RELEASE_DIR=release
LICENSE_FILENAME=LICENSE_$RELEASE_NAME

android update lib-project -p .
ant clean
ant release
if [ $? -ne 0 ]; then
    echo "build fail..."
    exit 1
fi
cd bin/
zip -u -r classes.jar ../src/**
cp ../../LICENSE ./$LICENSE_FILENAME
zip -u -r classes.jar ./$LICENSE_FILENAME
rm ./$LICENSE_FILENAME
mv classes.jar ../../$RELEASE_DIR/$RELEASE_NAME
