package com.eaglesakura.android.dao.net;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.eaglesakura.android.dao.net.DbNetCache;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DB_NET_CACHE.
*/
public class DbNetCacheDao extends AbstractDao<DbNetCache, String> {

    public static final String TABLENAME = "DB_NET_CACHE";

    /**
     * Properties of entity DbNetCache.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Url = new Property(0, String.class, "url", true, "URL");
        public final static Property CacheType = new Property(1, int.class, "cacheType", false, "CACHE_TYPE");
        public final static Property BodySize = new Property(2, int.class, "bodySize", false, "BODY_SIZE");
        public final static Property BlockSize = new Property(3, int.class, "blockSize", false, "BLOCK_SIZE");
        public final static Property DownloadedSize = new Property(4, int.class, "downloadedSize", false, "DOWNLOADED_SIZE");
        public final static Property Method = new Property(5, String.class, "method", false, "METHOD");
        public final static Property CacheTime = new Property(6, java.util.Date.class, "cacheTime", false, "CACHE_TIME");
        public final static Property CacheLimit = new Property(7, java.util.Date.class, "cacheLimit", false, "CACHE_LIMIT");
        public final static Property Etag = new Property(8, String.class, "etag", false, "ETAG");
        public final static Property Hash = new Property(9, String.class, "hash", false, "HASH");
    };


    public DbNetCacheDao(DaoConfig config) {
        super(config);
    }
    
    public DbNetCacheDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DB_NET_CACHE' (" + //
                "'URL' TEXT PRIMARY KEY NOT NULL UNIQUE ," + // 0: url
                "'CACHE_TYPE' INTEGER NOT NULL ," + // 1: cacheType
                "'BODY_SIZE' INTEGER NOT NULL ," + // 2: bodySize
                "'BLOCK_SIZE' INTEGER NOT NULL ," + // 3: blockSize
                "'DOWNLOADED_SIZE' INTEGER NOT NULL ," + // 4: downloadedSize
                "'METHOD' TEXT NOT NULL ," + // 5: method
                "'CACHE_TIME' INTEGER NOT NULL ," + // 6: cacheTime
                "'CACHE_LIMIT' INTEGER NOT NULL ," + // 7: cacheLimit
                "'ETAG' TEXT," + // 8: etag
                "'HASH' TEXT);"); // 9: hash
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DB_NET_CACHE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DbNetCache entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getUrl());
        stmt.bindLong(2, entity.getCacheType());
        stmt.bindLong(3, entity.getBodySize());
        stmt.bindLong(4, entity.getBlockSize());
        stmt.bindLong(5, entity.getDownloadedSize());
        stmt.bindString(6, entity.getMethod());
        stmt.bindLong(7, entity.getCacheTime().getTime());
        stmt.bindLong(8, entity.getCacheLimit().getTime());
 
        String etag = entity.getEtag();
        if (etag != null) {
            stmt.bindString(9, etag);
        }
 
        String hash = entity.getHash();
        if (hash != null) {
            stmt.bindString(10, hash);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DbNetCache readEntity(Cursor cursor, int offset) {
        DbNetCache entity = new DbNetCache( //
            cursor.getString(offset + 0), // url
            cursor.getInt(offset + 1), // cacheType
            cursor.getInt(offset + 2), // bodySize
            cursor.getInt(offset + 3), // blockSize
            cursor.getInt(offset + 4), // downloadedSize
            cursor.getString(offset + 5), // method
            new java.util.Date(cursor.getLong(offset + 6)), // cacheTime
            new java.util.Date(cursor.getLong(offset + 7)), // cacheLimit
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // etag
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // hash
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DbNetCache entity, int offset) {
        entity.setUrl(cursor.getString(offset + 0));
        entity.setCacheType(cursor.getInt(offset + 1));
        entity.setBodySize(cursor.getInt(offset + 2));
        entity.setBlockSize(cursor.getInt(offset + 3));
        entity.setDownloadedSize(cursor.getInt(offset + 4));
        entity.setMethod(cursor.getString(offset + 5));
        entity.setCacheTime(new java.util.Date(cursor.getLong(offset + 6)));
        entity.setCacheLimit(new java.util.Date(cursor.getLong(offset + 7)));
        entity.setEtag(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setHash(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(DbNetCache entity, long rowId) {
        return entity.getUrl();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(DbNetCache entity) {
        if(entity != null) {
            return entity.getUrl();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
